development:
  address: "smtp.gmail.com"
  port: 587
  domain: "gmail.com"
  authentication: "plain"
  user_name: <%= ENV["mail_server_user_name"] %>
  password: <%= ENV["mail_server_pwd"] %>
  enable_starttls_auto: true